"""
Configuration settings for the RAG chatbot application.
"""

import os
from typing import Optional
from pydantic import BaseSettings, validator, Field


class Settings(BaseSettings):
    """Application settings with validation."""
    
    # Database settings
    neon_database_url: str
    
    # Qdrant settings
    qdrant_url: str
    qdrant_api_key: Optional[str] = None # Qdrant API key might be optional if running locally without auth
    embedding_dimension: int = Field(384, description="Dimension of the embeddings generated by the model.")
    embedding_model_name: str = Field("all-MiniLM-L6-v2", description="Name of the embedding model used.")
    
    # AI service settings
    gemini_api_key: Optional[str] = None
    
    # Security settings
    security_salt: str = "default_salt_change_in_production"
    jwt_secret_key: str = "change_this_in_production"
    
    # Performance settings
    max_concurrent_requests: int = 100
    request_timeout: int = 30
    max_file_size: int = 10 * 1024 * 1024  # 10MB
    
    # Rate limiting
    rate_limit_requests: int = 100
    rate_limit_window: int = 60  # minutes
    
    # Logging
    log_level: str = "INFO"
    log_file: str = "app.log"
    
    # Environment
    environment: str = "development"
    debug: bool = False
    
    @validator('neon_database_url')
    def validate_database_url(cls, v):
        if not v or not v.startswith('postgresql'):
            raise ValueError('Invalid database URL')
        return v
    
    @validator('qdrant_url')
    def validate_qdrant_url(cls, v):
        if not v or not (v.startswith('http://') or v.startswith('https://')):
            raise ValueError('Invalid Qdrant URL')
        return v
            
    @validator('embedding_dimension')
    def validate_embedding_dimension(cls, v):
        if v <= 0:
            raise ValueError('Embedding dimension must be a positive integer')
        return v
    
    @validator('environment')
    def validate_environment(cls, v):
        if v not in ['development', 'staging', 'production']:
            raise ValueError('Environment must be development, staging, or production')
        return v
    
    @validator('security_salt')
    def validate_security_salt(cls, v):
        if v == "default_salt_change_in_production" and cls.environment == "production":
            raise ValueError('Must change security salt in production')
        return v
    
    class Config:
        env_file = ".env"
        case_sensitive = False


# Global settings instance
settings = Settings()


def get_settings() -> Settings:
    """Get application settings."""
    return settings


# Environment-specific configurations
class DevelopmentSettings(Settings):
    """Development environment settings."""
    debug: bool = True
    log_level: str = "DEBUG"


class ProductionSettings(Settings):
    """Production environment settings."""
    debug: bool = False
    log_level: str = "WARNING"
    
    @validator('jwt_secret_key')
    def validate_jwt_secret(cls, v):
        if v == "change_this_in_production":
            raise ValueError('Must change JWT secret in production')
        return v


def get_environment_settings() -> Settings:
    """Get environment-specific settings."""
    env = os.getenv("ENVIRONMENT", "development").lower()
    
    if env == "production":
        return ProductionSettings()
    else:
        return DevelopmentSettings()